[project]
name = "lagartixa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "jinja2>=3.1.6",
    "marko>=2.1.2",
    "pygments>=2.19.2",
    "pyyaml>=6.0.2",
    "watchdog>=6.0.0",
]
